### ISSUE TITLE
Swapped encoder Z pin on F407 board not updated in schematic

### ISSUE THREAD

**Issue by bjanders** [Ultrawipf/OpenFFBoard-hardware#3]
In commit 31e6b57c136df8f5c7ae9fc0cd2735a78ad29ff5 the encoder Z pin was updated on the board, but not in the schematic, and now the board and schematic are out of sync in the git repository. I verified that the board and schematic were in sync before this commit.

**Comment by Ultrawipf** [comment]
You are right. Updated the schematic and pdf to reflect the changes. According to eagle its back in sync for me.
