### ISSUE TITLE
Use board STM32F407VET6

### ISSUE THREAD

**Issue by active-game** [Ultrawipf/OpenFFBoard-hardware#4]
Is it possible to use Stm32f407vet6 modul without your board?  if so, which pins to connect to?

**Comment by blackneutron** [comment]
Did you get any answers?

**Comment by Ultrawipf** [comment]
Yes you can as long as your firmware build is smaller than 512k flash. Its otherwise identical to the F407VGT6.
This is currently the case but may not be in the future. Disabling features can decrease the size as well.
